### ISSUE TITLE
Does only work with APC currently

### ISSUE THREAD

**Issue by ThaDafinser** [HandsetDetection/php-apikit#38]
Since i saw the new release, i gave the lib another try to integrate it to https://github.com/ThaDafinser/UserAgentParser

But i could not finish it.

First off, the cache cannot be changed to another then APC
- the Cache instance does not receive parameters
  - https://github.com/HandsetDetection/php-apikit/blob/b70691b3038002a622ca69da11603fc4329d2dca/src/HDStore.php#L54
  - https://github.com/HandsetDetection/php-apikit/blob/b70691b3038002a622ca69da11603fc4329d2dca/src/HD4.php#L114

Some methods also have missing parameters, e.g.
https://github.com/HandsetDetection/php-apikit/blob/master/src/HD4.php#L242
https://github.com/HandsetDetection/php-apikit/blob/b70691b3038002a622ca69da11603fc4329d2dca/src/HDDevice.php#L115

**Comment by elricho** [comment]
Thanks for the report. We've confirmed the issues and will have a fix out shortly.

**Comment by elricho** [comment]
Hey @ThaDafinser, Issues should be sorted. Please try 4.1.1 at your leisure :-) Thanks.

**Comment by ThaDafinser** [comment]
@elricho the cache bug is fixed.

I have another issue, but i will open a new one

Thanks!
